### ISSUE TITLE
window.turnstile.render is not a function

### ISSUE THREAD

**Issue by nojaf** [marsidev/react-turnstile#69]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

The component does not load and I get `window.turnstile.render is not a function`:

```
react-dom.development.js:22878 Uncaught TypeError: window.turnstile.render is not a function
    at index.mjs:315:34
    at commitHookEffectListMount (react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24917:7)
    at commitPassiveMountEffects (react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27078:3)
    at flushPassiveEffects (react-dom.development.js:27023:14)
    at react-dom.development.js:26808:9
    at workLoop (scheduler.development.js:266:34)
(anonymous) @ index.mjs:315
commitHookEffectListMount @ react-dom.development.js:23189
commitPassiveMountOnFiber @ react-dom.development.js:24965
commitPassiveMountEffects_complete @ react-dom.development.js:24930
commitPassiveMountEffects_begin @ react-dom.development.js:24917
commitPassiveMountEffects @ react-dom.development.js:24905
flushPassiveEffectsImpl @ react-dom.development.js:27078
flushPassiveEffects @ react-dom.development.js:27023
(anonymous) @ react-dom.development.js:26808
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18704 The above error occurred in the <Turnstile> component:

    at http://localhost:4321/node_modules/.vite/deps/@marsidev_react-turnstile.js?v=d6b521a6:107:5
    at div
    at div
    at TicketForm (http://localhost:4321/src/components/tickets/TicketForm.res.mjs:249:36)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18704
update.callback @ react-dom.development.js:18737
callCallback @ react-dom.development.js:15036
commitUpdateQueue @ react-dom.development.js:15057
commitLayoutEffectOnFiber @ react-dom.development.js:23430
commitLayoutMountEffects_complete @ react-dom.development.js:24727
commitLayoutEffects_begin @ react-dom.development.js:24713
commitLayoutEffects @ react-dom.development.js:24651
commitRootImpl @ react-dom.development.js:26862
commitRoot @ react-dom.development.js:26721
performSyncWorkOnRoot @ react-dom.development.js:26156
flushSyncCallbacks @ react-dom.development.js:12042
flushPassiveEffectsImpl @ react-dom.development.js:27099
flushPassiveEffects @ react-dom.development.js:27023
(anonymous) @ react-dom.development.js:26808
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:12056 Uncaught TypeError: window.turnstile.render is not a function
    at index.mjs:315:34
    at commitHookEffectListMount (react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24917:7)
    at commitPassiveMountEffects (react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27078:3)
    at flushPassiveEffects (react-dom.development.js:27023:14)
    at react-dom.development.js:26808:9
    at workLoop (scheduler.development.js:266:34)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your [CodeSandbox](https://codesandbox.io/s/new) example below:**

I'm using the basic component:

```
<Turnstile siteKey={turnstileKey} onSuccess={updateTurnStileKey} />
```

**What is the expected behavior?**

turnstile should be loaded before used.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Seeing this both in latest Chrome and Firefox.

```
    "@marsidev/react-turnstile": "^0.6.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
```

Is it possible to load the script via

```
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>
```

And not tell the react component to load it?

**Comment by marsidev** [comment]
Please provide a minimal reproduction. You can use codesandbox, stackblitz, etc.

**Comment by nojaf** [comment]
Boy, I just figured it out. I had a container div element with an id of `turnstile`.
In HTML, every element with an id is added to the window object. So it was trying to call `render` on the DOM element🙃.
